-- AlterTable
ALTER TABLE `modelentity` ADD COLUMN `gender` ENUM('MALE', 'FEMALE', 'NON_BINARY', 'OTHER') NOT NULL DEFAULT 'MALE';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `gender` ENUM('MALE', 'FEMALE', 'NON_BINARY', 'OTHER') NOT NULL DEFAULT 'FEMALE';
